/*
 * iOS driver definitions
 *
 * Copyright 2024 Wine Project
 *
 * IMPORTANT: This code was generated by minimax-m2.7 AI model and has NOT been tested.
 * NO WARRANTY: This code is provided "as is" without any guarantees of functionality,
 * security, or reliability. Use at your own risk.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

#ifndef __WINE_IOS_H
#define __WINE_IOS_H

#include <stdarg.h>
#include <stdlib.h>
#include <pthread.h>

/* IOkit framework headers - available in iOS SDK */
#include <IOKit/IOKitLib.h>
#include <IOKit/graphics/IOGraphicsLib.h>
#include <IOKit/hid/IOHIDLib.h>
#include <IOKit/usb/IOUSBLib.h>
#include <IOKit/audio/IOAudioTypes.h>

#include "windef.h"
#include "winbase.h"
#include "ntgdi.h"
#include "wine/gdi_driver.h"
#include "ntuser.h"
#include "wine/unixlib.h"
#include "ios_native.h"


/**************************************************************************
 * IOkit interface declarations
 */

#define DECL_FUNCPTR(f) extern typeof(f) * p##f

/* Core IOkit functions */
DECL_FUNCPTR( IOServiceMatching );
DECL_FUNCPTR( IOServiceGetMatchingServices );
DECL_FUNCPTR( IOServiceOpen );
DECL_FUNCPTR( IOObjectRelease );
DECL_FUNCPTR( IORegistryEntryGetName );
DECL_FUNCPTR( IORegistryEntryCreateCFProperties );
DECL_FUNCPTR( IORegistryEntryGetPath );

/* Graphics IOkit functions */
DECL_FUNCPTR( CGDisplayIOSurfaceLock );
DECL_FUNCPTR( CGDisplayIOSurfaceUnlock );
DECL_FUNCPTR( CGDisplayCreateImageFromIOSurface );

/* HID IOkit functions */
DECL_FUNCPTR( IOHIDManagerCreate );
DECL_FUNCPTR( IOHIDManagerOpen );
DECL_FUNCPTR( IOHIDManagerClose );
DECL_FUNCPTR( IOHIDManagerSetDeviceMatching );
DECL_FUNCPTR( IOHIDManagerRegisterDeviceMatchingCallback );
DECL_FUNCPTR( IOHIDManagerRegisterDeviceRemovalCallback );

/* Audio IOkit functions */
DECL_FUNCPTR( AudioObjectGetPropertyData );
DECL_FUNCPTR( AudioObjectSetPropertyData );
DECL_FUNCPTR( AudioObjectAddPropertyListener );
DECL_FUNCPTR( AudioObjectRemovePropertyListener );

#undef DECL_FUNCPTR


/**************************************************************************
 * OpenGL/METAL driver
 */

extern UINT IOS_OpenGLInit( UINT version, const struct opengl_funcs *opengl_funcs, 
                            const struct opengl_driver_funcs **driver_funcs );

extern UINT IOS_MetalInit( UINT version, const struct metal_funcs *metal_funcs,
                           const struct metal_driver_funcs **driver_funcs );


/**************************************************************************
 * iOS pseudo-device
 */

extern void createDesktopView( int *event_source );
extern void register_native_view( HWND hwnd, void *view, BOOL client );
extern void *create_ioctl_view( HWND hwnd, BOOL metal );
extern void *grab_ioctl_view( void *view );
extern void release_ioctl_view( void *view );
extern void destroy_ioctl_view( HWND hwnd, BOOL metal );
extern int ioctl_view_pos_changed( HWND hwnd, const struct window_rects *rects,
                                   UINT style, UINT flags, HWND after, HWND owner );
extern int ioctl_set_view_parent( HWND hwnd, HWND parent );
extern int ioctl_set_capture( HWND hwnd );
extern int ioctl_set_cursor( int id, int width, int height,
                             int hotspotx, int hotspoty, const unsigned int *bits );


/**************************************************************************
 * USER driver
 */

extern pthread_mutex_t view_data_mutex;
extern INT IOS_GetKeyNameText( LONG lparam, LPWSTR buffer, INT size );
extern UINT IOS_MapVirtualKeyEx( UINT code, UINT maptype, HKL hkl );
extern SHORT IOS_VkKeyScanEx( WCHAR ch, HKL hkl );
extern void IOS_SetCursor( HWND hwnd, HCURSOR handle );
extern BOOL IOS_CreateDesktop( const WCHAR *name, UINT width, UINT height );
extern BOOL IOS_CreateWindow( HWND hwnd );
extern void IOS_SetDesktopWindow( HWND hwnd );
extern void IOS_DestroyWindow( HWND hwnd );
extern BOOL IOS_ProcessEvents( DWORD mask );
extern LRESULT IOS_DesktopWindowProc( HWND hwnd, UINT msg, WPARAM wp, LPARAM lp );
extern void IOS_SetParent( HWND hwnd, HWND parent, HWND old_parent );
extern void IOS_SetCapture( HWND hwnd, UINT flags, HWND previous );
extern UINT IOS_ShowWindow( HWND hwnd, INT cmd, RECT *rect, UINT swp );
extern LRESULT IOS_WindowMessage( HWND hwnd, UINT msg, WPARAM wp, LPARAM lp );
extern BOOL IOS_WindowPosChanging( HWND hwnd, UINT swp_flags, BOOL shaped, const struct window_rects *rects );
extern struct client_surface *IOS_CreateClientSurface( HWND hwnd, int pixel_format );
extern BOOL IOS_CreateWindowSurface( HWND hwnd, BOOL layered, const RECT *surface_rect, struct window_surface **surface );
extern void IOS_WindowPosChanged( HWND hwnd, HWND insert_after, HWND owner_hint, UINT swp_flags,
                                  const struct window_rects *new_rects, struct window_surface *surface );
extern void *get_client_view( HWND hwnd );
extern BOOL has_client_surface( HWND hwnd );

extern unsigned int screen_width;
extern unsigned int screen_height;
extern RECT virtual_screen_rect;
extern MONITORINFOEXW default_monitor;

enum ios_window_messages
{
    WM_IOS_REFRESH = WM_WINE_FIRST_DRIVER_MSG,
};

extern void init_monitors( int width, int height );
extern void set_screen_dpi( DWORD dpi );
extern void update_keyboard_lock_state( WORD vkey, UINT state );


/**************************************************************************
 * IOkit service management
 */

typedef struct _IOS_SERVICE
{
    io_service_t service;
    io_connect_t connect;
    CFTypeRef properties;
    char name[256];
    struct _IOS_SERVICE *next;
} IOS_SERVICE;

typedef struct _IOS_HID_DEVICE
{
    IOHIDDeviceRef device;
    struct _IOS_HID_DEVICE *next;
} IOS_HID_DEVICE;

/* IOkit service enumeration */
extern IOS_SERVICE *ios_find_service( const char *service_name );
extern IOS_SERVICE *ios_get_all_services( void );
extern void ios_release_services( IOS_SERVICE *services );
extern BOOL ios_service_open( IOS_SERVICE *service, int type, io_connect_t *connect );
extern void ios_service_close( IOS_SERVICE *service );

/* HID device management */
extern IOS_HID_DEVICE *ios_hid_enumerate( UInt32 usagePage, UInt32 usage );
extern void ios_hid_free_enumeration( IOS_HID_DEVICE *devices );
extern BOOL ios_hid_open( IOS_HID_DEVICE *device );
extern void ios_hid_close( IOS_HID_DEVICE *device );


/**************************************************************************
 * Display/Graphics IOkit integration
 */

typedef struct _IOS_DISPLAY
{
    CGDirectDisplayID display_id;
    uint32_t width;
    uint32_t height;
    uint32_t depth;
    uint32_t dpi;
    double scale;
    BOOL is_main;
    IOS_SERVICE *graphics_service;
    IOS_SERVICE *framebuffer_service;
    struct _IOS_DISPLAY *next;
} IOS_DISPLAY;

extern IOS_DISPLAY *ios_get_displays( void );
extern void ios_release_displays( IOS_DISPLAY *displays );
extern IOS_DISPLAY *ios_get_main_display( void );
extern BOOL ios_display_mode( IOS_DISPLAY *display, UINT32 width, UINT32 height, UINT32 depth );


/**************************************************************************
 * Audio IOkit integration  
 */

typedef struct _IOS_AUDIO_DEVICE
{
    AudioObjectID device_id;
    UInt32 transport_type;
    char name[256];
    BOOL is_input;
    BOOL is_output;
    struct _IOS_AUDIO_DEVICE *next;
} IOS_AUDIO_DEVICE;

extern IOS_AUDIO_DEVICE *ios_audio_enumerate_devices( BOOL input );
extern void ios_audio_free_enumeration( IOS_AUDIO_DEVICE *devices );
extern BOOL ios_audio_set_volume( AudioObjectID device, Float32 volume );


/**************************************************************************
 * Event handling
 */

enum ios_event_type
{
    IOS_DESKTOP_CHANGED,
    IOS_CONFIG_CHANGED,
    IOS_SURFACE_CHANGED,
    IOS_MOTION_EVENT,
    IOS_KEYBOARD_EVENT,
    IOS_HID_DEVICE_ADDED,
    IOS_HID_DEVICE_REMOVED,
    IOS_AUDIO_DEVICE_CHANGED
};

union ios_event_data
{
    enum ios_event_type type;
    struct
    {
        enum ios_event_type type;
        unsigned int    width;
        unsigned int    height;
    } desktop;
    struct
    {
        enum ios_event_type type;
        unsigned int    dpi;
    } cfg;
    struct
    {
        enum ios_event_type type;
        HWND            hwnd;
        BOOL            client;
        unsigned int    width;
        unsigned int    height;
    } surface;
    struct
    {
        enum ios_event_type type;
        HWND            hwnd;
        INPUT           input;
    } motion;
    struct
    {
        enum ios_event_type type;
        HWND            hwnd;
        UINT            lock_state;
        INPUT           input;
    } kbd;
    struct
    {
        enum ios_event_type type;
        IOS_HID_DEVICE *device;
    } hid;
    struct
    {
        enum ios_event_type type;
        IOS_AUDIO_DEVICE *device;
    } audio;
};

int ios_send_event( const union ios_event_data *data );

extern int event_source;


/**************************************************************************
 * Thread-safe event queue for main thread dispatch
 */

typedef struct _IOS_EVENT_QUEUE
{
    pthread_mutex_t mutex;
    pthread_cond_t cond;
    union ios_event_data *events;
    int capacity;
    int head;
    int tail;
    int count;
    BOOL shutdown;
} IOS_EVENT_QUEUE;

extern IOS_EVENT_QUEUE *ios_event_queue_create( int capacity );
extern void ios_event_queue_destroy( IOS_EVENT_QUEUE *queue );
extern int ios_event_queue_push( IOS_EVENT_QUEUE *queue, const union ios_event_data *event );
extern int ios_event_queue_pop( IOS_EVENT_QUEUE *queue, union ios_event_data *event, int timeout_ms );
extern void ios_event_queue_process( IOS_EVENT_QUEUE *queue );


/**************************************************************************
 * Metal-specific structures
 */

#ifdef OBJC_SELF
#import <Metal/Metal.h>
#import <QuartzCore/CAMetalLayer.h>
#import <UIKit/UIKit.h>

typedef struct _IOS_METAL_VIEW
{
    id<MTLDevice> device;
    id<MTLCommandQueue> command_queue;
    CAMetalLayer *metal_layer;
    UIView *ui_view;
    struct client_surface *client_surface;
    struct window_surface *window_surface;
    pthread_mutex_t lock;
    BOOL needs_display;
} IOS_METAL_VIEW;

extern IOS_METAL_VIEW *ios_metal_view_create( HWND hwnd, int width, int height );
extern void ios_metal_view_destroy( IOS_METAL_VIEW *view );
extern BOOL ios_metal_view_present( IOS_METAL_VIEW *view, IOS_SURFACE *surface );
extern id<MTLDevice> ios_metal_get_device( void );
extern id<MTLCommandQueue> ios_metal_get_command_queue( void );

#endif /* OBJC_SELF */


/**************************************************************************
 * IOkit notification callbacks
 */

extern void IOS_HIDDeviceCallback( void *context, IOReturn result, void *sender );
extern void IOS_HIDRemovalCallback( void *context, IOReturn result, void *sender );
extern void IOS_DisplayReconfigurationCallback( CGDirectDisplayID display, 
                                                  CGDisplayChangeSummaryFlags flags, 
                                                  void *userInfo );


/**************************************************************************
 * String conversion helpers
 */

static inline void ascii_to_unicode( WCHAR *dst, const char *src, size_t len )
{
    while (len--) *dst++ = (unsigned char)*src++;
}

static inline void unicode_to_ascii( char *dst, const WCHAR *src, size_t len )
{
    while (len--) *dst++ = (unsigned char)*src++;
}

static inline CFStringRef unicode_to_cfstring( const WCHAR *str )
{
    CFStringRef result;
    char ascii_buf[256];
    size_t len = 0;
    
    while (str[len] && len < sizeof(ascii_buf) - 1)
    {
        ascii_buf[len] = (char)str[len];
        len++;
    }
    ascii_buf[len] = 0;
    
    result = CFStringCreateWithCString( kCFAllocatorDefault, ascii_buf, kCFStringEncodingASCII );
    return result;
}


#endif  /* __WINE_IOS_H */
