/*
 * iOS native interface definitions
 *
 * Copyright 2024 Wine Project

    IMPORTANT: This code was generated by minimax-m2.7 AI model and has NOT been tested.
    NO WARRANTY: This code is provided "as is" without any guarantees of functionality,
    security, or reliability. Use at your own risk.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

#ifndef __WINE_IOS_NATIVE_H
#define __WINE_IOS_NATIVE_H

#include <CoreGraphics/CoreGraphics.h>
#include <CoreVideo/CoreVideo.h>
#include <IOSurface/IOSurface.h>

/*
 * Surface types for iOS rendering
 */

typedef struct _IOS_SURFACE
{
    IOSurfaceRef iosurface;
    CGContextRef context;
    void *buffer;
    int width;
    int height;
    int stride;
    int pixel_format;  /* kIOSurfacePixelFormat_* */
    BOOL is_locked;
    pthread_mutex_t lock;
} IOS_SURFACE;

/* Pixel formats */
#define kIOSurfacePixelFormat_32ARGB    0x00000020
#define kIOSurfacePixelFormat_32BGRA    0x00000021
#define kIOSurfacePixelFormat_565       0x00000005
#define kIOSurfacePixelFormat_5551      0x00000003
#define kIOSurfacePixelFormat_8888      0x00000022
#define kIOSurfacePixelFormat_888       0x00000002

/*
 * Surface operations
 */

IOS_SURFACE *ios_surface_create( int width, int height, int pixel_format );
void ios_surface_destroy( IOS_SURFACE *surface );
BOOL ios_surface_lock( IOS_SURFACE *surface, void **buffer, int *stride );
void ios_surface_unlock( IOS_SURFACE *surface );
void ios_surface_flush( IOS_SURFACE *surface );
CGImageRef ios_surface_create_cgimage( IOS_SURFACE *surface );

/*
 * Display link for synchronized rendering
 */

typedef struct _IOS_DISPLAY_LINK IOS_DISPLAY_LINK;

typedef void (*IOS_DISPLAY_LINK_CALLBACK)( IOS_DISPLAY_LINK *link, void *user_info );

struct _IOS_DISPLAY_LINK_CALLBACK_INFO
{
    IOS_DISPLAY_LINK_CALLBACK callback;
    void *user_info;
};

IOS_DISPLAY_LINK *ios_display_link_create( IOS_DISPLAY_LINK_CALLBACK callback, void *user_info );
void ios_display_link_destroy( IOS_DISPLAY_LINK *link );
void ios_display_link_start( IOS_DISPLAY_LINK *link );
void ios_display_link_stop( IOS_DISPLAY_LINK *link );
void ios_display_link_set_paused( IOS_DISPLAY_LINK *link, BOOL paused );
double ios_display_link_get_duration( IOS_DISPLAY_LINK *link );
double ios_display_link_get_timestamp( IOS_DISPLAY_LINK *link );

/*
 * Touch/Multi-touch support
 */

typedef struct _IOS_TOUCH_POINT
{
    NSInteger touch_id;
    NSInteger finger_id;
    CGPoint location;
    CGPoint previous_location;
    CGFloat major_radius;
    CGFloat force;
    CGFloat azimuth_angle;
    CGFloat altitude_angle;
    UITouchPhase phase;
    NSTimeInterval timestamp;
} IOS_TOUCH_POINT;

typedef struct _IOS_TOUCH_EVENT
{
    IOS_TOUCH_POINT *touches;
    int touch_count;
    IOS_TOUCH_POINT **all_touches;
    int all_touch_count;
    UITouchPhase phase;
    UIEvent *ui_event;
    UIView *view;
} IOS_TOUCH_EVENT;

/*
 * Keyboard event conversion
 */

typedef struct _IOS_KEYBOARD_MAPPING
{
    UITextInputMode input_mode;
    UIKey *ui_key;
    WCHAR vk_char;
    WCHAR scan_char;
    UINT modifiers;
} IOS_KEYBOARD_MAPPING;

WCHAR ios_keyboard_translate_key( UIKey *ui_key, UINT *modifiers );
WCHAR ios_keyboard_translate_char( unichar character, UINT key_code, UINT modifiers );

/*
 * Memory mapping for iOS
 */

void *ios_mmap( void *addr, size_t len, int prot, int flags, int fd, off_t offset );
int ios_munmap( void *addr, size_t len );
int ios_msync( void *addr, size_t len, int flags );

/*
 * Thread synchronization with Grand Central Dispatch
 */

typedef dispatch_queue_t IOS_DISPATCH_QUEUE;
typedef dispatch_group_t IOS_DISPATCH_GROUP;
typedef dispatch_source_t IOS_DISPATCH_SOURCE;

IOS_DISPATCH_QUEUE ios_dispatch_get_main_queue( void );
IOS_DISPATCH_QUEUE ios_dispatch_queue_create( const char *label );
void ios_dispatch_queue_release( IOS_DISPATCH_QUEUE queue );

void ios_dispatch_async( IOS_DISPATCH_QUEUE queue, void (^block)(void) );
void ios_dispatch_sync( IOS_DISPATCH_QUEUE queue, void (^block)(void) );
void ios_dispatch_barrier_async( IOS_DISPATCH_QUEUE queue, void (^block)(void) );

IOS_DISPATCH_GROUP ios_dispatch_group_create( void );
void ios_dispatch_group_release( IOS_DISPATCH_GROUP group );
void ios_dispatch_group_enter( IOS_DISPATCH_GROUP group );
void ios_dispatch_group_leave( IOS_DISPATCH_GROUP group );
void ios_dispatch_group_wait( IOS_DISPATCH_GROUP group, dispatch_time_t timeout );
void ios_dispatch_group_notify( IOS_DISPATCH_GROUP group, IOS_DISPATCH_QUEUE queue, void (^block)(void) );

IOS_DISPATCH_SOURCE ios_dispatch_source_create( dispatch_source_type_t type,
                                                uintptr_t handle,
                                                unsigned long mask,
                                                IOS_DISPATCH_QUEUE queue );
void ios_dispatch_source_release( IOS_DISPATCH_SOURCE source );
void ios_dispatch_source_set_event_handler( IOS_DISPATCH_SOURCE source, void (^handler)(void) );
void ios_dispatch_source_set_cancel_handler( IOS_DISPATCH_SOURCE source, void (^handler)(void) );
void ios_dispatch_source_resume( IOS_DISPATCH_SOURCE source );
void ios_dispatch_source_suspend( IOS_DISPATCH_SOURCE source );
uintptr_t ios_dispatch_source_get_handle( IOS_DISPATCH_SOURCE source );
unsigned long ios_dispatch_source_get_data( IOS_DISPATCH_SOURCE source );

/*
 * Objective-C runtime bridge
 */

Class ios_objc_getClass( const char *name );
SEL ios_objc_getSel( const char *name );
void *ios_objc_msgSend( void *receiver, SEL selector, ... );
void *ios_objc_msgSendSuper( void *super_struct, SEL selector, ... );

/*
 * View hierarchy management
 */

@interface WineViewController : UIViewController
{
    HWND wine_hwnd;
    UIView *client_view;
    BOOL is_opengl;
    BOOL is_metal;
}

@property(nonatomic, assign) HWND wineHwnd;
@property(nonatomic, strong) UIView *clientView;
@property(nonatomic, assign) BOOL isOpenGL;
@property(nonatomic, assign) BOOL isMetal;

- (instancetype)initWithHwnd:(HWND)hwnd;
- (void)setupOpenGLView;
- (void)setupMetalView;
- (void)handleTouchEvent:(UIEvent *)event;
- (void)handleKeyboardEvent:(UIKey *)key;

@end

@interface WineApplicationDelegate : NSObject <UIApplicationDelegate>
{
    UIWindow *main_window;
    NSMutableArray *view_controllers;
    IOS_EVENT_QUEUE *event_queue;
}

@property(nonatomic, strong) UIWindow *mainWindow;
@property(nonatomic, strong) NSMutableArray *viewControllers;
@property(nonatomic, assign) IOS_EVENT_QUEUE *eventQueue;

- (void)setupMainWindow;
- (WineViewController *)createViewControllerForHwnd:(HWND)hwnd;
- (void)postEvent:(const union ios_event_data *)event;

@end

/*
 * Notifications
 */

extern NSString *const kIOSNotificationDisplayChanged;
extern NSString *const kIOSNotificationDeviceAdded;
extern NSString *const kIOSNotificationDeviceRemoved;
extern NSString *const kIOSNotificationMemoryPressure;
extern NSString *const kIOSNotificationTerminating;

void ios_post_notification( NSString *name, NSDictionary *userInfo );

/*
 * Power management
 */

typedef struct _IOS_POWER_INFO
{
    UIDeviceBatteryState battery_state;
    float battery_level;
    BOOL low_power_mode_enabled;
    BOOL thermal_state_normal;
} IOS_POWER_INFO;

BOOL ios_get_power_info( IOS_POWER_INFO *info );
void ios_register_power_notifications( void (^handler)(IOS_POWER_INFO *info) );

/*
 * Network access
 */

typedef struct _IOS_NETWORK_INTERFACE
{
    char name[64];
    char ip_address[64];
    BOOL is_up;
    BOOL is_wifi;
    BOOL is_cellular;
} IOS_NETWORK_INTERFACE;

IOS_NETWORK_INTERFACE *ios_enumerate_network_interfaces( int *count );
void ios_free_network_interfaces( IOS_NETWORK_INTERFACE *interfaces );

/*
 * File system access
 */

char *ios_get_documents_path( void );
char *ios_get_cache_path( void );
char *ios_get_tmp_path( void );
BOOL ios_create_directory_at_path( const char *path );
BOOL ios_remove_item_at_path( const char *path );

/*
 * Bundle resources
 */

const char *ios_get_bundle_path( void );
CFURLRef ios_get_resource_url( const char *name, const char *type );

#endif  /* __WINE_IOS_NATIVE_H */
